"""Add users table

Revision ID: 31ef1fcdbba2
Revises: 
Create Date: 2024-11-14 10:25:52.021476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31ef1fcdbba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('motor', schema=None) as batch_op:
        batch_op.alter_column('gambar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motor', schema=None) as batch_op:
        batch_op.alter_column('gambar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
